export const MOCK_USER = {
  name: 'Rahul Sharma',
  phone: '+91 98765 43210',
  avatar: null,
  plan: 'Premium',
};

export const MOCK_STICKERS = [
  {
    id: 'stk_001',
    vehicleName: "Rahul's Innova",
    registration: 'MH12AB1234',
    type: 'car',
    color: 'White',
    status: 'active',
    lastScanned: '2 hours ago',
    scanCount: 14,
    openIncidents: 1,
    docCount: 2,
  },
  {
    id: 'stk_002',
    vehicleName: 'Priya Scooty',
    registration: 'MH12XY9876',
    type: 'bike',
    color: 'Red',
    status: 'active',
    lastScanned: '3 days ago',
    scanCount: 3,
    openIncidents: 0,
    docCount: 1,
  },
  {
    id: 'stk_003',
    vehicleName: "Dad's Swift",
    registration: 'DL01CD5678',
    type: 'car',
    color: 'Silver',
    status: 'paused',
    lastScanned: '12 days ago',
    scanCount: 6,
    openIncidents: 0,
    docCount: 3,
  },
];

export const MOCK_INCIDENTS = [
  {
    id: 'inc_001',
    stickerName: "Rahul's Innova",
    registration: 'MH12AB1234',
    type: 'wrong_parking',
    severity: 'medium',
    status: 'open',
    reportedBy: 'Anonymous Scanner',
    reportedAgo: '14 min ago',
    message: 'Your car is blocking the narrow lane near Gate 3. Please move it soon.',
    hasPhoto: true,
    escalationLevel: 0,
  },
  {
    id: 'inc_002',
    stickerName: "Rahul's Innova",
    registration: 'MH12AB1234',
    type: 'lights_on',
    severity: 'low',
    status: 'resolved',
    reportedBy: 'Verified User',
    reportedAgo: '2 days ago',
    message: 'Headlights are on in parking slot B-12.',
    hasPhoto: false,
    escalationLevel: 0,
  },
  {
    id: 'inc_003',
    stickerName: 'Priya Scooty',
    registration: 'MH12XY9876',
    type: 'blocking_exit',
    severity: 'high',
    status: 'resolved',
    reportedBy: 'Security Guard',
    reportedAgo: '5 days ago',
    message: 'Scooter blocking Tower B exit ramp.',
    hasPhoto: false,
    escalationLevel: 1,
  },
];

export const MOCK_DOCUMENTS = [
  {
    id: 'doc_001',
    vehicleName: "Rahul's Innova",
    type: 'rc',
    label: 'Registration Certificate',
    expiry: '2027-03-15',
    daysLeft: 670,
    status: 'valid',
    access: 'emergency_contacts',
  },
  {
    id: 'doc_002',
    vehicleName: "Rahul's Innova",
    type: 'insurance',
    label: 'Car Insurance Policy',
    expiry: '2026-06-30',
    daysLeft: 46,
    status: 'expiring',
    access: 'private',
  },
  {
    id: 'doc_003',
    vehicleName: "Rahul's Innova",
    type: 'puc',
    label: 'PUC Certificate',
    expiry: '2026-05-25',
    daysLeft: 10,
    status: 'expiring',
    access: 'private',
  },
  {
    id: 'doc_004',
    vehicleName: 'Priya Scooty',
    type: 'insurance',
    label: 'Two-Wheeler Insurance',
    expiry: '2027-01-10',
    daysLeft: 240,
    status: 'valid',
    access: 'private',
  },
];

export const MOCK_SCAN_HISTORY = [
  { id: 'sc_001', sticker: "Rahul's Innova", type: 'wrong_parking', scanner: 'Anonymous', time: '14 min ago', hasLocation: true },
  { id: 'sc_002', sticker: "Rahul's Innova", type: 'general', scanner: 'Anonymous', time: '2h ago', hasLocation: false },
  { id: 'sc_003', sticker: "Rahul's Innova", type: 'lights_on', scanner: 'Verified User', time: '2 days ago', hasLocation: true },
  { id: 'sc_004', sticker: 'Priya Scooty', type: 'blocking_exit', scanner: 'Security Guard', time: '5 days ago', hasLocation: true },
  { id: 'sc_005', sticker: "Dad's Swift", type: 'general', scanner: 'Anonymous', time: '12 days ago', hasLocation: false },
];

export const GUARD_VEHICLES = [
  { plate: 'MH12AB1234', type: 'car', color: 'White', flat: 'A-403', tower: 'Tower A', resident: 'Rahul S.', incidents: 2 },
  { plate: 'MH12XY9876', type: 'bike', color: 'Red', flat: 'B-204', tower: 'Tower B', resident: 'Priya M.', incidents: 0 },
  { plate: 'KA01CD5678', type: 'car', color: 'Silver', flat: 'C-101', tower: 'Tower C', resident: 'Suresh K.', incidents: 1 },
];
